### ISSUE TITLE
does getaddressInfo work with the latest node-windows image?

### ISSUE THREAD

**Issue by panmanphil** [StefanScherer/dockerfiles-windows#349]
using docker compose and the stock mongodb container, I have a node app that uses an env var MONGODB_URI=mongodb://db:27017 to specify a connection string. db is defined in the compose file and within the node container I can ping db and a resolved address. If I changed the connection string to use the ip address the app works. using "db" instead, no joy, a ENOTFOUND is returned from getAddressInfo. Any issues with docker networking in windows these days?

```
version: '3'

networks:
  dbnet:
    driver: nat

services:
  db:
    image: mongo:4.0-windowsservercore-1803
    networks:
      - dbnet
  web:
    build: .
    ports:
     - "8080:8080"
    networks:
      - dbnet
    environment:
     - MONGODB_URI=mongodb://172.22.135.164:27017/test
     - MONGODBXX_URI=mongodb://db:27017/test
    depends_on: 
     - db 
    volumes:
     - c:\temp:C:\starter
     ```
