### ISSUE TITLE
Getting an error when running compose up

### ISSUE THREAD

**Issue by lmayorga1980** [StefanScherer/dockerfiles-windows#418]
Could this be related since the C:\vagrant is the mount from the osx filesystem into my windows core server with docker?

```
version: "3.2"

services:
  web:
    build: .
    command: nodemon.cmd --inspect=0.0.0.0:9229 app.js
    working_dir: C:\code
    volumes:
      - C:\vagrant\dockerfiles\nodejs:c:\code

    ports:
      - "8000:8000"
      - "9229:9229"

networks:
  default:
    external:
      name: nat

```

**output**

```
PS C:\vagrant\dockerfiles\nodejs> docker-compose up
Creating nodejs_web_1 ... done
Attaching to nodejs_web_1
web_1  | [nodemon] 1.19.1
web_1  | [nodemon] to restart at any time, enter `rs`
web_1  | [nodemon] watching: *.*
web_1  | [nodemon] starting `node --inspect=0.0.0.0:9229 app.js`
web_1  | Debugger listening on ws://0.0.0.0:9229/96b13148-d57b-4f3a-a171-cfbde15f2e31
web_1  | For help, see: https://nodejs.org/en/docs/inspector
web_1  | [nodemon] Internal watch failed: EISDIR: illegal operation on a directory, watch 'C:\code'
nodejs_web_1 exited with code 1
```
